پیشنهاد فیلم به کاربر بر اساس مشخصات فیلم نظیر ژانر.

در ابتدا کتابخانه های مورد نیاز رو وارد میکنیم یا فرامیخونیم

In [1]:
import pandas as pd
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

دو فایل لازم برای انجام پروژه که یکی حاوی مشخصات فیلم ها و دیگری حاوی امتیاز کاربران به فیلم ها هست رو میخونیم.

In [ ]:
movies_df = pd.read_csv('movies.csv')
ratings_df = pd.read_csv('ratings.csv')
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

همونطور که مشاهده میکنید سال و عنوان فیلم در کنار یکدیگر در یک ستون حضور دارند پس برای مرتب کردن داده ها با استفاده از لامبدا سال رو وارد ستون جدیدی میکنیم به این شکل که ابتدا سال رو جدا میکنیم سپس پرانتز ها رو حذف کنیم و وارد ستون جدیدی میکنیم .سپس سال رو از از ستون (عنوان)حذف میکنیم.سپس فضای خالی موجود در دو سمت عنوان فیلم ها رو پاک میکنیم. داده هارو پس از این تغییرات مشاهده میکنید

In [3]:
movies_df['year'] = movies_df.title.str.extract('(\(\d\d\d\d\))',expand=False)
movies_df['year'] = movies_df.year.str.extract('(\d\d\d\d)',expand=False)
movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())
movies_df.head()

C:\Users\rihane\AppData\Local\Temp/ipykernel_12548/1075324330.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  movies_df['title'] = movies_df.title.str.replace('(\(\d\d\d\d\))', '')

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

حالا نوبت به مرتب و خوانا کردن بخش ژانر میرسه تابه راحتی از داده ها استفاده کنیم.به این شکل که داده های ژانر رو در بخش هایی که(|) داره جدا میکنیم و میبیند که به صورت یک لیست دیده میشه . داده هارو پس از این تغییرات مشاهده میکنید

In [4]:
movies_df['genres'] = movies_df.genres.str.split('|')
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995

ما میخوایم برای استفاده راحت تر از ژانر فیلم ها به جای کلمه از اعداد صفر و یک استفاده کنیم . به این شکل که اگر فیلمی ژانر مورد نظر رو داره عدد یک میدیم و اگر نداره عدد صفر. خب برای انجام اینکار یک کپی از دیتای مشخصات فیلم ها میگیریم ما در اولین مورد خودمون نیازی به به استفاده از اطلاعات ژانر نداریم.سپس میایم یکی یکی روی تمام ردیف ها حرکت میکنیم و با توجه به ژانر های گفته شده در ستون ژانر در صورت ستونی با نام همون ژانر بنویس 1 سپس جاهای که یک فیلم به علت نداشتن اون ژانر داده ای وجود نداره 0 رو بنویس.دیتا رو پس از این تغییرات مشاهده میکنید

In [5]:
moviesWithGenres_df = movies_df.copy()

for index, row in movies_df.iterrows():
    for genre in row['genres']:
        moviesWithGenres_df.at[index, genre] = 1
moviesWithGenres_df = moviesWithGenres_df.fillna(0)
moviesWithGenres_df.head()

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,...,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men,"[Comedy, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II,[Comedy],1995,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

بعد از مرتب شدن دیتای قبیل میریم سراغ دیتایی که حاوی امتیازات کاربران به فیلم ها است.
بخش ابتدایی دیتا رو میبینید.

In [6]:
ratings_df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

باید این دیتا رو هم ساده مرتب و خوانا کنیم برای همین ستون زمان رو به علت اینکه به اون نیاز نداریم پاک میکنیم. دیتا رو بدون ستون زمان مشاهده میکنید

In [7]:
ratings_df = ratings_df.drop('timestamp', 1)
ratings_df.head()

C:\Users\rihane\AppData\Local\Temp/ipykernel_12548/3809009477.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  ratings_df = ratings_df.drop('timestamp', 1)

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

در این بخش اطلاعات و امتیازات قبلی کاربر مورد نظری که میخوایم بهش فیلم پیشنهاد بکنیم رو به صورت لیستی از دیکشنری ها وارد میکنیم. سپس اطلاعات رو به یک دیتا فریم تبدیل میکنیم. اطلاعات رو به صورت یک دیتا فریم مشاهده میکنید

In [8]:
userInput = [
            {'title':'Breakfast Club, The', 'rating':5},
            {'title':'Toy Story', 'rating':3.5},
            {'title':'Jumanji', 'rating':2},
            {'title':"Pulp Fiction", 'rating':5},
            {'title':'Akira', 'rating':4.5}
         ] 
inputMovies = pd.DataFrame(userInput)
inputMovies

                 title  rating
0  Breakfast Club, The     5.0
1            Toy Story     3.5
2              Jumanji     2.0
3         Pulp Fiction     5.0
4                Akira     4.5

در این بخش میخوایم آی دی فیلم هایی که کاربر ما نگاه کرده رو دربیاریم برای همین از لیست اطلاعات کلی فیلم هایی که داشتیم ستون عنوان فیلم رو با ستون عنوان دیتا های کار بر مدنظرمون تطابق میدیم و اطلاعات فیلم هارو از دیتای فیلم ها جدا میکنیم و بعد با اطلاعات ورودی کاربرمون ترکیب میکنیم سپس زمان و ژانر رو از دیتامون جدا میکنیم چون بهش نیازی نداریم .دیتای نهایی که شامل آی دی فیلم و عنوان فیلم و امتیاز کاربرمون هست رو مشاهده میکنید.

In [9]:
inputId = movies_df[movies_df['title'].isin(inputMovies['title'].tolist())]
inputMovies = pd.merge(inputId, inputMovies)
inputMovies = inputMovies.drop('genres', 1).drop('year', 1)
inputMovies

C:\Users\rihane\AppData\Local\Temp/ipykernel_12548/2584586099.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  inputMovies = inputMovies.drop('genres', 1).drop('year', 1)

   movieId                title  rating
0        1            Toy Story     3.5
1        2              Jumanji     2.0
2      296         Pulp Fiction     5.0
3     1274                Akira     4.5
4     1968  Breakfast Club, The     5.0

در دیتای بالا ما ژانر رو که در ابتدای کار با اعداد 0 و 1 مشخص کرده بودیم رو نداریم پس آی دی فیلم های کاربرمون رو با دیتای مرتب شده حاوی ژانرمون که بالاتر داشتیم تطابق میدیم و اطلاعات فیلم های کاربرمون که شامل ژانر و سال ساخت فیلم میشه رو جدا میکنیم که دیتای حاصل شده رو مشاهده میکنید

In [10]:
userMovies = moviesWithGenres_df[moviesWithGenres_df['movieId'].isin(inputMovies['movieId'].tolist())]
userMovies

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,...,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
257,296,Pulp Fiction,"[Comedy, Crime, Drama, Thriller]",1994,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
973,1274,Akira,"[Action, Adventure, Animation, Sci-Fi]",1988,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1445,1968,"Breakfast Club, The","[Comedy, Drama]",1985,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

در این بخش برای مرتب تر کردن دیتا ابتدا ایندکس ها رو که اعداد مختلفی هستن رو مرتب میکنه و از صفر الی اخر مینویسه . بعد بخش هایی مثل ستون های آی دی فیلم و عنوان فیلم و ژانر و سال رو حذف میکنه.دیتای حاصل رو مشاهده میکنید

In [11]:
userMovies = userMovies.reset_index(drop=True)
userGenreTable = userMovies.drop('movieId', 1).drop('title', 1).drop('genres', 1).drop('year', 1)
userGenreTable

C:\Users\rihane\AppData\Local\Temp/ipykernel_12548/638483878.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  userGenreTable = userMovies.drop('movieId', 1).drop('title', 1).drop('genres', 1).drop('year', 1)

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
inputMovies['rating']

0    3.5
1    2.0
2    5.0
3    4.5
4    5.0
Name: rating, dtype: float64

در این بخش امتیازات کاربرمون به هر فیلم رو ضرب میکنیم در دیتای ژانر های هر فیلم که بالا تر مرتبشون کردیم و مجموع اعداد ضرب شده برای هر ژانر رو مشاهده میکنید.

In [13]:
userProfile = userGenreTable.transpose().dot(inputMovies['rating'])
userProfile

Adventure             10.0
Animation              8.0
Children               5.5
Comedy                13.5
Fantasy                5.5
Romance                0.0
Drama                 10.0
Action                 4.5
Crime                  5.0
Thriller               5.0
Horror                 0.0
Mystery                0.0
Sci-Fi                 4.5
War                    0.0
Musical                0.0
Documentary            0.0
IMAX                   0.0
Western                0.0
Film-Noir              0.0
(no genres listed)     0.0
dtype: float64

دیتا فریمی رو که ابتدای کار داشتیم و حاوی اطلاعات تمامی فیلم های موجود بود رو بر اساس ستون ای دی فیلم ها ست میکنیم بعد ستون هایی نظیر عنوان فیلم و سال ساخت و ژانر و ای دی فیلم رو جدا میکنیم. که نتیجه رو مشاهده میکنید.

In [14]:
genreTable = moviesWithGenres_df.set_index(moviesWithGenres_df['movieId'])
genreTable = genreTable.drop('movieId', 1).drop('title', 1).drop('genres', 1).drop('year', 1)
genreTable.head()

C:\Users\rihane\AppData\Local\Temp/ipykernel_12548/2603148.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  genreTable = genreTable.drop('movieId', 1).drop('title', 1).drop('genres', 1).drop('year', 1)

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
movieId,,,,,,,,,,,,,,,,,,,,
1,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

میبنید که دیتای ما شامل 9742 ردیف و 20 ستون هست.

In [15]:
genreTable.shape

(9742, 20)

برای مشخص شدن فیلم های نزدیک به سلیقه کاربر ما ،در این بخش دیتای ژانر کل فیلم ها رو در دیتایی که شامل نمرات بدست امده هر ژانر که پروفایل کاربر ما رو تشکیل میداد ضرب میکنیم و مجموعش رو تقسیم میکنیم بر مجموع دیتای پروفایل کاربرمون که نتیجه رو مشاهده میکنید.عدد های حاصل هر چه بزرگتر باشن به سلیقه کاربر ما نزدیک تر هست .

In [16]:
recommendationTable_df = ((genreTable*userProfile).sum(axis=1))/(userProfile.sum())
recommendationTable_df.head()

movieId
1    0.594406
2    0.293706
3    0.188811
4    0.328671
5    0.188811
dtype: float64

برای مشاهده اعداد  بر اساس بزرگیشون اونها رو مرتب میکنیم. ترتیب اعداد از زیاد به کم رو مشاهده میکنید و فیلم های نزدیک تر به بالای جدول به سلیقه احتمالی کاربر ما نزدیکتر هستند .

In [17]:
recommendationTable_df = recommendationTable_df.sort_values(ascending=False)
recommendationTable_df.head()

movieId
134853    0.734266
148775    0.685315
117646    0.678322
6902      0.678322
81132     0.671329
dtype: float64

 در قسمت بالا فقط ایدی فیلم ها رو داشتیم پس در این بخش بر اساس ایدی 20 فیلم بالای جدول یا دیتا سایر مشخصات فیلم ها رو نظیر عنوان و ژانر و سال ساخت از دیتای اولیه ای که شامل مشخصات کل فیلم های موجود بود رو استخراج میکنیم دیتای به دست امده ای که مشاهد میکنید شامل بیست فیلم هستند که به سلیقه کاربر ما احتمالا نزدیک هستند و میتوانیم اونها رو به کاربرمون پیشنهاد بدیم.

In [18]:
movies_df.loc[movies_df['movieId'].isin(recommendationTable_df.head(20).keys())]

,movieId,title,genres,year
559,673,Space Jam,"[Adventure, Animation, Children, Comedy, Fanta...",1996
1390,1907,Mulan,"[Adventure, Animation, Children, Comedy, Drama...",1998
2250,2987,Who Framed Roger Rabbit?,"[Adventure, Animation, Children, Comedy, Crime...",1988
3460,4719,Osmosis Jones,"[Action, Animation, Comedy, Crime, Drama, Roma...",2001
4631,6902,Interstate 60,"[Adventure, Comedy, Drama, Fantasy, Mystery, S...",2002
5490,26340,"Twelve Tasks of Asterix, The (Les douze travau...","[Action, Adventure, Animation, Children, Comed...",1976
5819,32031,Robots,"[Adventure, Animation, Children, Comedy, Fanta...",2005
6047,40339,Chicken Little,"[Action, Adventure, Animation, Children, Comed...",2005
6448,51939,TMNT (Teenage Mutant Ninja Turtles),"[Action, Adventure, Animation, Children, Comed...",2007
6455,52287,Meet the Robinsons,"[Action, Adventure, Animation, Children, Comed...",2007
6879,62956,Futurama: Bender's Game,"[Action, Adventure, Animation, Comedy, Fantasy...",2008
7441,81132,Rubber,"[Action, Adventure, Comedy, Crime, Drama, Film...",2010
7550,85261,Mars Needs Moms,"[Action, Adventure, Animation, Children, Comed...",2011
8349,108540,Ernest & Célestine (Ernest et Célestine),"[Adventure, Animation, Children, Comedy, Drama...",2012
8357,108932,The Lego Movie,"[Action, Adventure, Animation, Children, Comed...",2014
8597,117646,Dragonheart 2: A New Beginning,"[Action, Adventure, Comedy, Drama, Fantasy, Th...",2000
8806,130520,Home,"[Adventure, Animation, Children, Comedy, Fanta...",2015
8900,134853,Inside Out,"[Adventure, Animation, Children, Comedy, Drama...",2015
9169,148775,Wizards of Waverly Place: The Movie,"[Adventure, Children, Comedy, Drama, Fantasy, ...",2009
9282,157865,Ratchet & Clank,"[Action, Adventure, Animation, Children, Comed...",2016